# .goreleaser.yml
# Build customization
builds:
  - binary: cfft-client
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: zip
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - docs/*